# initialize: setup.json
# 10,000 ether is placed in the NaiveReceiverEchidna contract.
balanceContract: 10000000000000000000000
# Allow for multi-abi use
multi-abi: true
# multi-abi was renamed in echidna >= 2.1
allContracts: true
# provide solc remappings to crytic-compile
cryticArgs: ['--solc-remaps', '@=node_modules/@ hardhat=node_modules/hardhat']
# cryticArgs: ['--ignore-compile']
# Number of sequences of transactions to generate during testing
testLimit: 10000
# Number of transactions to generate during testing
seqLen: 1000